import { UilWifi, UilMonitor, UilGlobe, UilExclamationTriangle, UilSignalAlt, UilRobot, UilBolt, UilRss, UilSearchAlt, UilDesktop, UilHeartbeat, UilBell, UilChartBar, UilShield, UilClock, UilCalendarAlt, UilChartLine, UilHeartRate, UilBug, UilLink, UilServer, UilDatabase, UilLock, UilEnvelope } from "@iconscout/react-unicons";
import type { WidgetDef } from "./types";

import CyberPulseWidget from "./widgets/CyberPulseWidget";
import IntelCategoryWidget from "./widgets/IntelCategoryWidget";
import CommandCenterWidget from "./widgets/CommandCenterWidget";
import ClockWidget from "./widgets/ClockWidget";
import CalendarWidget from "./widgets/CalendarWidget";
import StatusBarWidget from "./widgets/StatusBarWidget";
import NetworkStatusWidget from "./widgets/NetworkStatusWidget";
import QuickActionsWidget from "./widgets/QuickActionsWidget";
import SystemHealthWidget from "./widgets/SystemHealthWidget";
import VPSHealthWidget from "./widgets/VPSHealthWidget";
import CVEAlertsWidget from "./widgets/CVEAlertsWidget";
import ThreatIntelWidget from "./widgets/ThreatIntelWidget";
import AgentActivityWidget from "./widgets/AgentActivityWidget";
import FeedWidget from "./widgets/FeedWidget";
import LiveFeedWidget from "./widgets/LiveFeedWidget";
import ShodanMonitorWidget from "./widgets/ShodanMonitorWidget";
import FleetWidget from "./widgets/FleetWidget";
import UptimeMonitorWidget from "./widgets/UptimeMonitorWidget";
import AlertCenterWidget from "./widgets/AlertCenterWidget";
import AnalyticsWidget from "./widgets/AnalyticsWidget";
import HuntWidget from "./widgets/HuntWidget";

export const widgetRegistry: WidgetDef[] = [
  {
    id: "cyber-pulse",
    name: "Cyber Pulse",
    description: "Global threat activity — live IOC counts, threat level, feed breakdown",
    category: "intel",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: CyberPulseWidget,
    icon: UilHeartRate,
  },
  {
    id: "command-center",
    name: "Command Center",
    description: "CrowByte branding header",
    category: "system",
    defaultSize: "1x1",
    component: CommandCenterWidget,
    icon: UilShield,
    compact: true,
  },
  {
    id: "clock",
    name: "World Clock",
    description: "Multi-timezone clocks — add/remove timezones",
    category: "system",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "3x1", "4x1"],
    component: ClockWidget,
    icon: UilClock,
    compact: true,
  },
  {
    id: "calendar",
    name: "Calendar",
    description: "Mini calendar with multiple date format support",
    category: "tools",
    defaultSize: "1x1",
    component: CalendarWidget,
    icon: UilCalendarAlt,
    compact: true,
  },
  {
    id: "network-status",
    name: "Network Status",
    description: "IP address, VPN status, DNS leak detection",
    category: "system",
    defaultSize: "4x1",
    component: NetworkStatusWidget,
    desktopOnly: true,
    icon: UilWifi,
  },
  {
    id: "quick-actions",
    name: "Quick Actions",
    description: "Fast navigation to key tools",
    category: "tools",
    defaultSize: "4x1",
    component: QuickActionsWidget,
    icon: UilBolt,
  },
  {
    id: "system-health",
    name: "System Health",
    description: "CPU, memory, disk, GPU usage on your local machine",
    category: "system",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: SystemHealthWidget,
    desktopOnly: true,
    icon: UilMonitor,
  },
  {
    id: "vps-health",
    name: "VPS Health",
    description: "OpenClaw VPS metrics, agent swarm status",
    category: "system",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: VPSHealthWidget,
    desktopOnly: true,
    icon: UilGlobe,
  },
  {
    id: "feed",
    name: "Security Feed",
    description: "Personalized security intelligence from CrowByte agents",
    category: "intel",
    defaultSize: "4x1",
    component: FeedWidget,
    icon: UilRss,
  },
  {
    id: "cve-alerts",
    name: "CVE Alerts",
    description: "Latest critical vulnerabilities tracked by Sentinel",
    category: "security",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: CVEAlertsWidget,
    icon: UilExclamationTriangle,
  },
  {
    id: "threat-intel",
    name: "Threat Intelligence",
    description: "Live cyber threat news from RSS feeds, analyzed by AI",
    category: "intel",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: ThreatIntelWidget,
    icon: UilSignalAlt,
  },
  {
    id: "agent-activity",
    name: "Agent Activity",
    description: "AI agent swarm status — Sentinel, Alerter, Classifier, Reporter",
    category: "agents",
    defaultSize: "4x1",
    component: AgentActivityWidget,
    icon: UilRobot,
  },
  {
    id: "live-feed",
    name: "Live Feed",
    description: "Scrolling news ticker with cyber threat headlines",
    category: "intel",
    defaultSize: "4x1",
    component: LiveFeedWidget,
    icon: UilSignalAlt,
  },
  {
    id: "shodan-monitor",
    name: "Shodan Monitor",
    description: "Internet exposure alerts from Shodan for your assets",
    category: "security",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: ShodanMonitorWidget,
    icon: UilSearchAlt,
  },
  {
    id: "fleet",
    name: "Fleet Monitor",
    description: "Quick view of all endpoints — status, CPU, memory",
    category: "system",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: FleetWidget,
    icon: UilDesktop,
  },
  {
    id: "uptime-monitor",
    name: "Uptime Monitor",
    description: "HTTP health checks on your services and endpoints",
    category: "system",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: UptimeMonitorWidget,
    icon: UilHeartbeat,
  },
  {
    id: "alert-center",
    name: "Alert Center",
    description: "SIEM alert summary — severity breakdown and recent alerts",
    category: "security",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: AlertCenterWidget,
    icon: UilBell,
  },
  {
    id: "analytics",
    name: "Analytics",
    description: "Usage stats, API calls, top services quick view",
    category: "tools",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: AnalyticsWidget,
    icon: UilChartBar,
  },
  {
    id: "hunt-mode",
    name: "Hunt Mode",
    description: "Active hunt status — capture rate, auto-flags, proxy state, triage queue",
    category: "security",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: HuntWidget,
    icon: UilSearchAlt,
    desktopOnly: true,
  },
  // ═══ Intel Category Widgets ═══
  {
    id: "intel-malware",
    name: "Malware URLs",
    description: "Live malware URL indicators from URLhaus and ThreatFox",
    category: "intel",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: IntelCategoryWidget,
    icon: UilBug,
    config: { category: "malware_urls" },
  },
  {
    id: "intel-phishing",
    name: "Phishing Feed",
    description: "Active phishing URLs from OpenPhish",
    category: "intel",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: IntelCategoryWidget,
    icon: UilLink,
    config: { category: "phishing" },
  },
  {
    id: "intel-c2",
    name: "C2 Servers",
    description: "Command & Control server IPs from Feodo Tracker",
    category: "intel",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: IntelCategoryWidget,
    icon: UilServer,
    config: { category: "c2_servers" },
  },
  {
    id: "intel-bruteforce",
    name: "Brute Force IPs",
    description: "SSH/FTP/IMAP brute force attacker IPs",
    category: "intel",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: IntelCategoryWidget,
    icon: UilShield,
    config: { category: "brute_force" },
  },
  {
    id: "intel-compromised",
    name: "Compromised IPs",
    description: "Known compromised IPs from CINS, ET, GreenSnow, IPsum",
    category: "intel",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: IntelCategoryWidget,
    icon: UilExclamationTriangle,
    config: { category: "compromised_ips" },
  },
  {
    id: "intel-vulns",
    name: "Vulnerabilities",
    description: "CISA KEV known exploited vulns and CIRCL CVEs",
    category: "intel",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: IntelCategoryWidget,
    icon: UilDatabase,
    config: { category: "vulnerabilities" },
  },
  {
    id: "intel-iocs",
    name: "IOC Feed",
    description: "Mixed indicators of compromise from ThreatFox",
    category: "intel",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: IntelCategoryWidget,
    icon: UilBolt,
    config: { category: "iocs" },
  },
  {
    id: "intel-ip-rep",
    name: "IP Reputation",
    description: "IP reputation data from DShield and AlienVault",
    category: "intel",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: IntelCategoryWidget,
    icon: UilSearchAlt,
    config: { category: "ip_reputation" },
  },
  {
    id: "intel-web-attacks",
    name: "Web Attacks",
    description: "Apache attack IPs from Blocklist.de",
    category: "intel",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: IntelCategoryWidget,
    icon: UilGlobe,
    config: { category: "web_attacks" },
  },
  {
    id: "intel-spam",
    name: "Spam IPs",
    description: "Mail spam attacker IPs from Blocklist.de",
    category: "intel",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: IntelCategoryWidget,
    icon: UilEnvelope,
    config: { category: "spam" },
  },
  {
    id: "intel-oss-vulns",
    name: "OSS Vulns",
    description: "Open source package vulnerabilities from OSV.dev",
    category: "intel",
    defaultSize: "2x1",
    allowedSizes: ["2x1", "4x1"],
    component: IntelCategoryWidget,
    icon: UilLock,
    config: { category: "oss_vulns" },
  },
  {
    id: "status-bar",
    name: "Status Bar",
    description: "Vertical threat level, alerts, CVEs, findings, uptime bars",
    category: "security",
    defaultSize: "1x2",
    allowedSizes: ["1x2"],
    component: StatusBarWidget,
    icon: UilChartLine,
  },
];

export function getWidgetDef(id: string): WidgetDef | undefined {
  return widgetRegistry.find(w => w.id === id);
}
